### ISSUE TITLE
Permission to use chars

### ISSUE THREAD

**Issue by TomClarkson** [dierat/chinese_quiz_meteor_2#1]
I am making an open source quiz app to enter into this contest. https://gist.github.com/brentvatne/7d88f846417452355b18 

Could I please use your character list for the app? 

https://github.com/dierat/learn_hanzi/blob/development/chars.js

Many thanks,
Tom

**Comment by dierat** [comment]
Yes, go ahead! Here is a spreadsheet version in case that's easier for you to work with:

https://docs.google.com/spreadsheets/d/1_o74D8l2tZRKhzDMrc-omJvQM03B-vAvtq7k6Jztkds/

Sorry I didn't see this before. Lemme know if you need anything else!
